from django.conf import settings

TAG_NAME_MAX_LENGTH = 32
TAG_SLUG_MAX_LENGTH = 32
INGREDIENT_NAME_MAX_LENGTH = 128
MEASUREMENT_UNIT_MAX_LENGTH = 64
RECIPE_NAME_MAX_LENGTH = 256
MIN_COOKING_TIME = 1
MAX_COOKING_TIME = 32000
MIN_AMOUNT = 1
MAX_AMOUNT = 32000
DEFAULT_TEXT_LENGTH = 30
SHORT_LINK_BASE = 16
DATA_DIR_NAME = 'data'
INGREDIENTS_FILE = 'ingredients.json'
INGREDIENTS_PATHS = (
    settings.BASE_DIR / DATA_DIR_NAME / INGREDIENTS_FILE,
    settings.BASE_DIR.parent / DATA_DIR_NAME / INGREDIENTS_FILE,
)
